name: book_finder
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  email_validator: ^2.1.17
  cloud_firestore: ^4.6.0

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

